# backend/services/invoice_service.py

import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont


# Register a font that supports Indian Rupee ₹
FONT_PATH = "backend/invoices/DejaVuSans.ttf"

if os.path.exists(FONT_PATH):
    pdfmetrics.registerFont(TTFont("DejaVu", FONT_PATH))
    DEFAULT_FONT = "DejaVu"
else:
    DEFAULT_FONT = "Helvetica"   # fallback


class InvoiceService:

    # -------------------------------------------------------------
    # Utility: Format currency safely
    # -------------------------------------------------------------
    @staticmethod
    def _format_currency(amount):
        try:
            num = float(amount)
            return f"₹{num:,.2f}"
        except:
            return f"₹{amount}"

    # -------------------------------------------------------------
    # Utility: Ensure date is formatted properly
    # -------------------------------------------------------------
    @staticmethod
    def _format_date(date_value):
        if isinstance(date_value, datetime):
            return date_value.strftime("%d %B %Y, %I:%M %p")

        try:
            dt = datetime.fromisoformat(date_value)
            return dt.strftime("%d %B %Y, %I:%M %p")
        except:
            return str(date_value)

    # -------------------------------------------------------------
    # Main PDF Generator
    # -------------------------------------------------------------
    @staticmethod
    def generate_invoice_pdf(data: dict, filename: str):
        """
        Generate a professional invoice PDF.
        Zero emojis. Banking-safe formatting.
        """

        # Ensure output directory
        output_dir = os.path.dirname(filename)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir, exist_ok=True)

        # Create PDF
        doc = SimpleDocTemplate(
            filename,
            pagesize=A4,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )

        styles = getSampleStyleSheet()

        header_style = ParagraphStyle(
            'header_style',
            parent=styles['Title'],
            fontName=DEFAULT_FONT,
            fontSize=22,
            alignment=1,
        )

        subtitle_style = ParagraphStyle(
            'subtitle_style',
            parent=styles['Normal'],
            fontName=DEFAULT_FONT,
            fontSize=12,
            alignment=1,
            textColor=colors.grey,
        )

        body_style = ParagraphStyle(
            'body_style',
            parent=styles['Normal'],
            fontName=DEFAULT_FONT,
            fontSize=11,
            leading=16
        )

        # Build elements
        elements = []

        # ---------------------------------------------------
        # Header
        # ---------------------------------------------------
        elements.append(Paragraph("FinBuddy Transaction Invoice", header_style))
        elements.append(Paragraph("Secure • Verified • Generated by FinBuddy AI", subtitle_style))
        elements.append(Spacer(1, 20))

        # ---------------------------------------------------
        # Transaction Table
        # ---------------------------------------------------

        tx_id = data.get("id") or "AUTO-GENERATED"
        tx_date = InvoiceService._format_date(data.get("date", datetime.now()))
        amount_fmt = InvoiceService._format_currency(data.get("amount", 0))

        table_data = [
            ["Transaction ID", tx_id],
            ["Transaction Type", data.get("txn_type", "N/A")],
            ["Amount", amount_fmt],
            ["Counterparty", data.get("counterparty", "N/A")],
            ["Category", data.get("category", "N/A")],
            ["Date", tx_date],
        ]

        table = Table(table_data, colWidths=[140, 350])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
            ("FONTNAME", (0, 0), (-1, -1), DEFAULT_FONT),
            ("FONTSIZE", (0, 0), (-1, -1), 11),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("BOX", (0, 0), (-1, -1), 0.75, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 25))

        # ---------------------------------------------------
        # AI Insights
        # ---------------------------------------------------
        insight_text = data.get("ai_insight") or "No insights available."

        insight_box = [
            [Paragraph("<b>AI Insight</b>", body_style)],
            [Paragraph(insight_text, body_style)]
        ]

        insight_table = Table(insight_box, colWidths=[490])
        insight_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), colors.lightgrey),
            ("BACKGROUND", (0, 1), (0, 1), colors.whitesmoke),
            ("BOX", (0, 0), (-1, -1), 0.75, colors.grey),
            ("FONTNAME", (0, 0), (-1, -1), DEFAULT_FONT),
            ("FONTSIZE", (0, 0), (-1, -1), 11),
            ("LEADING", (0, 1), (-1, -1), 14),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 1), (-1, 1), 8),
            ("RIGHTPADDING", (0, 1), (-1, 1), 8),
        ]))

        elements.append(insight_table)
        elements.append(Spacer(1, 30))

        # ---------------------------------------------------
        # Footer
        # ---------------------------------------------------
        generated_on = datetime.now().strftime("%d %B %Y, %I:%M %p")
        footer_style = ParagraphStyle(
            'footer',
            parent=styles['Normal'],
            fontName=DEFAULT_FONT,
            fontSize=9,
            textColor=colors.grey,
            alignment=1
        )

        elements.append(Paragraph(f"Generated by FinBuddy AI • {generated_on}", footer_style))

        # Build PDF
        doc.build(elements)

        return filename
